# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Graphs(object):
    def setupUi(self, Graphs):
        Graphs.setObjectName("Graphs")
        Graphs.resize(834, 617)
        self.centralwidget = QtWidgets.QWidget(Graphs)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 831, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 460, 521, 112))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.sin = QtWidgets.QPushButton(self.formLayoutWidget)
        self.sin.setObjectName("sin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sin)
        self.cos = QtWidgets.QPushButton(self.formLayoutWidget)
        self.cos.setObjectName("cos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cos)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.tg = QtWidgets.QPushButton(self.formLayoutWidget)
        self.tg.setObjectName("tg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.tg)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.P = QtWidgets.QPushButton(self.formLayoutWidget)
        self.P.setObjectName("P")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.P)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_4)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(0, 410, 141, 51))
        self.clear.setObjectName("clear")
        self.goback = QtWidgets.QPushButton(self.centralwidget)
        self.goback.setGeometry(QtCore.QRect(140, 410, 111, 51))
        self.goback.setObjectName("goback")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(520, 410, 301, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.plus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.plus.setObjectName("plus")
        self.gridLayout.addWidget(self.plus, 2, 0, 1, 1)
        self.minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.minus.setObjectName("minus")
        self.gridLayout.addWidget(self.minus, 2, 1, 1, 1)
        self.cal_result = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_result.setObjectName("cal_result")
        self.gridLayout.addWidget(self.cal_result, 7, 1, 1, 1)
        self.cal_tg = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_tg.setObjectName("cal_tg")
        self.gridLayout.addWidget(self.cal_tg, 5, 2, 1, 1)
        self.cal_sin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_sin.setObjectName("cal_sin")
        self.gridLayout.addWidget(self.cal_sin, 5, 0, 1, 1)
        self.cal_cos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_cos.setObjectName("cal_cos")
        self.gridLayout.addWidget(self.cal_cos, 5, 1, 1, 1)
        self.multiplication = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multiplication.setObjectName("multiplication")
        self.gridLayout.addWidget(self.multiplication, 2, 2, 1, 1)
        self.cal_p = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_p.setObjectName("cal_p")
        self.gridLayout.addWidget(self.cal_p, 7, 2, 1, 1)
        self.cal_back = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_back.setObjectName("cal_back")
        self.gridLayout.addWidget(self.cal_back, 3, 1, 1, 1)
        self.devision = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.devision.setObjectName("devision")
        self.gridLayout.addWidget(self.devision, 3, 0, 1, 1)
        self.cal_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cal_clear.setObjectName("cal_clear")
        self.gridLayout.addWidget(self.cal_clear, 3, 2, 1, 1)
        self.cal_dop_funk = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cal_dop_funk.setText("")
        self.cal_dop_funk.setObjectName("cal_dop_funk")
        self.gridLayout.addWidget(self.cal_dop_funk, 0, 0, 1, 3)
        Graphs.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Graphs)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        Graphs.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Graphs)
        self.statusbar.setObjectName("statusbar")
        Graphs.setStatusBar(self.statusbar)

        self.retranslateUi(Graphs)
        QtCore.QMetaObject.connectSlotsByName(Graphs)

    def retranslateUi(self, Graphs):
        _translate = QtCore.QCoreApplication.translate
        Graphs.setWindowTitle(_translate("Graphs", "Постройка графика"))
        self.sin.setText(_translate("Graphs", "a*sin(b*x)+c"))
        self.cos.setText(_translate("Graphs", "a*cos(b*x)+c"))
        self.label_2.setText(_translate("Graphs", "Задаваемые переменные: a,b"))
        self.tg.setText(_translate("Graphs", "a*tg(b*x)+c"))
        self.label_3.setText(_translate("Graphs", "Задаваемые переменные: a,b"))
        self.P.setText(_translate("Graphs", "многочлен"))
        self.label_4.setText(_translate("Graphs", "Задаваемые переменные: коэфициенты при степенях многочлена"))
        self.label.setText(_translate("Graphs", "Задаваемые переменные: a,b"))
        self.clear.setText(_translate("Graphs", "Очистить"))
        self.goback.setText(_translate("Graphs", "Назад"))
        self.plus.setText(_translate("Graphs", "+"))
        self.minus.setText(_translate("Graphs", "-"))
        self.cal_result.setText(_translate("Graphs", "="))
        self.cal_tg.setText(_translate("Graphs", "a*tg(b*x)+c"))
        self.cal_sin.setText(_translate("Graphs", "a*sin(b*x)+c"))
        self.cal_cos.setText(_translate("Graphs", "a*cos(b*x)+c"))
        self.multiplication.setText(_translate("Graphs", "*"))
        self.cal_p.setText(_translate("Graphs", "многочлен"))
        self.cal_back.setText(_translate("Graphs", "back"))
        self.devision.setText(_translate("Graphs", "/"))
        self.cal_clear.setText(_translate("Graphs", "clear"))

from pyqtgraph import PlotWidget
